package com.anysoftkeyboard.gesturetyping;

import static com.anysoftkeyboard.keyboards.ExternalAnyKeyboardTest.SIMPLE_KeyboardDimens;
import static com.anysoftkeyboard.keyboards.Keyboard.KEYBOARD_ROW_MODE_NORMAL;

import android.content.Context;
import android.graphics.Point;
import androidx.core.util.Pair;
import androidx.test.core.app.ApplicationProvider;
import com.anysoftkeyboard.AnySoftKeyboardRobolectricTestRunner;
import com.anysoftkeyboard.keyboards.AnyKeyboard;
import com.anysoftkeyboard.keyboards.Keyboard;
import com.anysoftkeyboard.rx.TestRxSchedulers;
import com.menny.android.anysoftkeyboard.AnyApplication;
import com.menny.android.anysoftkeyboard.R;
import io.reactivex.disposables.Disposable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicReference;
import java.util.function.Function;
import java.util.stream.Stream;
import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Ignore;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(AnySoftKeyboardRobolectricTestRunner.class)
public class GestureTypingDetectorTest {
  private static final int MAX_SUGGESTIONS = 4;
  private List<Keyboard.Key> mKeys;
  private GestureTypingDetector mDetectorUnderTest;
  private AtomicReference<GestureTypingDetector.LoadingState> mCurrentState;
  private Disposable mSubscribeState;

  private static Stream<Point> generateTraceBetweenPoints(final Point start, final Point end) {
    int callsToMake = 16;
    final float stepX = (end.x - start.x) / (float) callsToMake;
    final float stepY = (end.y - start.y) / (float) callsToMake;

    List<Point> points = new ArrayList<>(1 + callsToMake);
    while (callsToMake >= 0) {
      points.add(
          new Point(end.x - (int) (callsToMake * stepX), end.y - (int) (callsToMake * stepY)));

      callsToMake--;
    }

    return points.stream();
  }

  private Point getPointForCharacter(final int character) {
    return mKeys.stream()
        .filter(key -> key.getPrimaryCode() == character)
        .findFirst()
        .map(key -> new Point(key.centerX, key.centerY))
        .orElseGet(
            () -> {
              throw new RuntimeException("Could not find key for character " + character);
            });
  }

  @Before
  public void setUp() {
    final Context context = ApplicationProvider.getApplicationContext();
    final AnyKeyboard keyboard =
        AnyApplication.getKeyboardFactory(context)
            .getAddOnById(context.getString(R.string.main_english_keyboard_id))
            .createKeyboard(KEYBOARD_ROW_MODE_NORMAL);
    keyboard.loadKeyboard(SIMPLE_KeyboardDimens);
    TestRxSchedulers.drainAllTasks();
    mKeys = keyboard.getKeys();

    mDetectorUnderTest =
        new GestureTypingDetector(
            context.getResources().getDimension(R.dimen.gesture_typing_frequency_factor),
            MAX_SUGGESTIONS,
            context.getResources().getDimensionPixelSize(R.dimen.gesture_typing_min_point_distance),
            mKeys);

    mCurrentState = new AtomicReference<>();
    mSubscribeState =
        mDetectorUnderTest
            .state()
            .subscribe(
                mCurrentState::set,
                throwable -> {
                  throw new RuntimeException(throwable);
                });

    Assert.assertEquals(GestureTypingDetector.LoadingState.NOT_LOADED, mCurrentState.get());

    // 2000 most common words in English
    // https://en.wiktionary.org/wiki/Wiktionary:Frequency_lists/Contemporary_fiction 
    String[] words = {
        "the",
        "I",
        "to",
        "and",
        "a",
        "of",
        "was",
        "he",
        "you",
        "it",
        "in",
        "her",
        "she",
        "that",
        "my",
        "his",
        "me",
        "on",
        "with",
        "at",
        "as",
        "had",
        "for",
        "but",
        "him",
        "said",
        "be",
        "up",
        "out",
        "look",
        "so",
        "have",
        "what",
        "not",
        "just",
        "like",
        "go",
        "they",
        "is",
        "this",
        "from",
        "all",
        "we",
        "were",
        "back",
        "do",
        "one",
        "about",
        "know",
        "if",
        "when",
        "get",
        "then",
        "into",
        "would",
        "no",
        "there",
        "I'm",
        "could",
        "don't",
        "ask",
        "down",
        "time",
        "didn't",
        "want",
        "eye",
        "them",
        "over",
        "your",
        "are",
        "or",
        "been",
        "now",
        "an",
        "by",
        "think",
        "see",
        "hand",
        "it's",
        "say",
        "how",
        "around",
        "head",
        "did",
        "well",
        "before",
        "off",
        "who",
        "more",
        "even",
        "turn",
        "come",
        "smile",
        "way",
        "really",
        "can",
        "face",
        "other",
        "some",
        "right",
        "their",
        "only",
        "walk",
        "make",
        "got",
        "try",
        "something",
        "room",
        "again",
        "thing",
        "after",
        "still",
        "thought",
        "door",
        "here",
        "too",
        "little",
        "because",
        "why",
        "away",
        "let",
        "take",
        "two",
        "start",
        "good",
        "where",
        "never",
        "through",
        "day",
        "much",
        "tell",
        "wasn't",
        "girl",
        "feel",
        "oh",
        "you're",
        "call",
        "talk",
        "will",
        "long",
        "than",
        "us",
        "made",
        "friend",
        "knew",
        "open",
        "need",
        "first",
        "which",
        "people",
        "that's",
        "went",
        "sure",
        "seem",
        "stop",
        "voice",
        "very",
        "felt",
        "took",
        "our",
        "pull",
        "laugh",
        "man",
        "okay",
        "close",
        "any",
        "came",
        "told",
        "love",
        "watch",
        "arm",
        "anything",
        "I'll",
        "though",
        "put",
        "left",
        "work",
        "guy",
        "hair",
        "next",
        "couldn't",
        "yeah",
        "while",
        "mean",
        "home",
        "few",
        "saw",
        "place",
        "school",
        "help",
        "wait",
        "late",
        "year",
        "can't",
        "house",
        "happen",
        "last",
        "always",
        "move",
        "old",
        "night",
        "nod",
        "life",
        "give",
        "sit",
        "stare",
        "sat",
        "should",
        "moment",
        "another",
        "behind",
        "side",
        "sound",
        "once",
        "find",
        "toward",
        "boy",
        "ever",
        "nothing",
        "front",
        "mother",
        "name",
        "am",
        "since",
        "reply",
        "he's",
        "myself",
        "leave",
        "bed",
        "new",
        "car",
        "use",
        "mind",
        "maybe",
        "has",
        "heard",
        "answer",
        "minute",
        "yes",
        "until",
        "both",
        "found",
        "end",
        "small",
        "I'd",
        "word",
        "someone",
        "same",
        "enough",
        "began",
        "run",
        "bit",
        "sigh",
        "each",
        "those",
        "almost",
        "against",
        "everything",
        "most",
        "thank",
        "wouldn't",
        "mom",
        "better",
        "play",
        "I've",
        "own",
        "every",
        "hard",
        "remember",
        "three",
        "stood",
        "live",
        "stand",
        "second",
        "sorry",
        "keep",
        "finally",
        "point",
        "gave",
        "already",
        "actually",
        "probably",
        "himself",
        "big",
        "everyone",
        "guess",
        "lot",
        "step",
        "hey",
        "hear",
        "light",
        "quickly",
        "dad",
        "kiss",
        "black",
        "pick",
        "else",
        "soon",
        "shoulder",
        "table",
        "best",
        "without",
        "notice",
        "stay",
        "care",
        "phone",
        "reach",
        "realize",
        "follow",
        "decide",
        "kind",
        "she's",
        "grab",
        "he'd",
        "show",
        "inside",
        "suddenly",
        "father",
        "rest",
        "herself",
        "grin",
        "hour",
        "hope",
        "also",
        "body",
        "might",
        "hadn't",
        "floor",
        "its",
        "continue",
        "ran",
        "across",
        "hold",
        "cry",
        "half",
        "pretty",
        "great",
        "course",
        "mouth",
        "class",
        "kid",
        "miss",
        "wonder",
        "morning",
        "least",
        "nice",
        "dark",
        "slowly",
        "done",
        "change",
        "doesn't",
        "together",
        "yet",
        "question",
        "anyway",
        "bad",
        "blue",
        "believe",
        "week",
        "God",
        "lip",
        "Mr.",
        "sleep",
        "fine",
        "what's",
        "family",
        "many",
        "worry",
        "roll",
        "parent",
        "under",
        "surprise",
        "water",
        "onto",
        "we're",
        "glance",
        "wall",
        "between",
        "seen",
        "read",
        "window",
        "idea",
        "white",
        "push",
        "feet",
        "must",
        "such",
        "seat",
        "set",
        "please",
        "red",
        "brother",
        "these",
        "whole",
        "lean",
        "part",
        "person",
        "slightly",
        "pass",
        "shook",
        "fact",
        "wrong",
        "gone",
        "far",
        "hit",
        "finger",
        "quite",
        "hate",
        "meet",
        "finish",
        "heart",
        "book",
        "past",
        "kill",
        "reason",
        "anyone",
        "figure",
        "top",
        "along",
        "world",
        "she'd",
        "high",
        "shirt",
        "does",
        "today",
        "young",
        "held",
        "outside",
        "listen",
        "whisper",
        "won't",
        "happy",
        "ground",
        "deep",
        "drop",
        "shrug",
        "dress",
        "fell",
        "there's",
        "yell",
        "breath",
        "air",
        "tear",
        "sister",
        "chair",
        "kitchen",
        "matter",
        "hurt",
        "fall",
        "wear",
        "isn't",
        "woman",
        "eat",
        "lie",
        "hell",
        "suppose",
        "cover",
        "couple",
        "large",
        "either",
        "five",
        "leg",
        "jump",
        "die",
        "return",
        "able",
        "bag",
        "alone",
        "shut",
        "stuff",
        "short",
        "ready",
        "understand",
        "kept",
        "plan",
        "raise",
        "street",
        "different",
        "problem",
        "break",
        "line",
        "early",
        "cut",
        "cold",
        "paper",
        "scream",
        "instead",
        "stupid",
        "silence",
        "tree",
        "caught",
        "ear",
        "food",
        "full",
        "four",
        "cause",
        "fuck",
        "explain",
        "expect",
        "fight",
        "exactly",
        "sort",
        "completely",
        "men",
        "dance",
        "met",
        "story",
        "whatever",
        "build",
        "speak",
        "glass",
        "pain",
        "check",
        "glare",
        "corner",
        "Mrs.",
        "chest",
        "hot",
        "rather",
        "month",
        "real",
        "touch",
        "park",
        "bring",
        "they're",
        "drink",
        "ago",
        "force",
        "you've",
        "fast",
        "lost",
        "attention",
        "wish",
        "mark",
        "wave",
        "shout",
        "fill",
        "begin",
        "baby",
        "interest",
        "money",
        "fun",
        "green",
        "however",
        "cheek",
        "mine",
        "clear",
        "brown",
        "forward",
        "near",
        "picture",
        "may",
        "cool",
        "drive",
        "hug",
        "shake",
        "sense",
        "alright",
        "you'll",
        "dream",
        "hang",
        "clothes",
        "act",
        "become",
        "manage",
        "meant",
        "game",
        "ignore",
        "stair",
        "taken",
        "party",
        "add",
        "sometimes",
        "job",
        "ten",
        "shot",
        "date",
        "quiet",
        "gaze",
        "group",
        "loud",
        "straight",
        "dead",
        "neck",
        "beside",
        "pause",
        "number",
        "conversation",
        "chance",
        "we'll",
        "rose",
        "quietly",
        "town",
        "blood",
        "color",
        "desk",
        "dinner",
        "hall",
        "horse",
        "music",
        "brought",
        "piece",
        "anymore",
        "beautiful",
        "order",
        "fire",
        "office",
        "true",
        "although",
        "warm",
        "easy",
        "enter",
        "perfect",
        "mutter",
        "softly",
        "cross",
        "shock",
        "smirk",
        "damn",
        "soft",
        "stomach",
        "snap",
        "spoke",
        "tire",
        "box",
        "catch",
        "skin",
        "teacher",
        "middle",
        "note",
        "yourself",
        "haven't",
        "lunch",
        "tomorrow",
        "breathe",
        "clean",
        "except",
        "appear",
        "lock",
        "knock",
        "bathroom",
        "movie",
        "agree",
        "offer",
        "kick",
        "form",
        "confuse",
        "lay",
        "less",
        "calm",
        "slip",
        "weren't",
        "sign",
        "dog",
        "lift",
        "immediately",
        "arrive",
        "deal",
        "tonight",
        "usually",
        "case",
        "frown",
        "shop",
        "scare",
        "promise",
        "mum",
        "couch",
        "pay",
        "state",
        "shit",
        "wrap",
        "pocket",
        "hello",
        "free",
        "huge",
        "ride",
        "bother",
        "land",
        "known",
        "especially",
        "expression",
        "carry",
        "ring",
        "spot",
        "allow",
        "several",
        "aren't",
        "during",
        "empty",
        "lady",
        "eyebrow",
        "strange",
        "coffee",
        "road",
        "threw",
        "wide",
        "bus",
        "forget",
        "gotten",
        "smell",
        "fear",
        "press",
        "boyfriend",
        "blonde",
        "throw",
        "round",
        "sun",
        "tall",
        "glad",
        "age",
        "write",
        "upon",
        "hide",
        "became",
        "crowd",
        "rain",
        "save",
        "trouble",
        "annoy",
        "nose",
        "weird",
        "death",
        "beat",
        "tone",
        "trip",
        "six",
        "control",
        "nearly",
        "consider",
        "gonna",
        "join",
        "learn",
        "above",
        "hi",
        "obviously",
        "entire",
        "direction",
        "foot",
        "angry",
        "power",
        "strong",
        "quick",
        "doctor",
        "edge",
        "song",
        "asleep",
        "twenty",
        "barely",
        "remain",
        "child",
        "enjoy",
        "gun",
        "slow",
        "city",
        "broke",
        "key",
        "lead",
        "throat",
        "normal",
        "you'd",
        "somewhere",
        "wake",
        "pair",
        "sky",
        "funny",
        "business",
        "student",
        "giggle",
        "bright",
        "admit",
        "jeans",
        "given",
        "children",
        "store",
        "sweet",
        "low",
        "climb",
        "rub",
        "apartment",
        "knee",
        "shoe",
        "attack",
        "bedroom",
        "joke",
        "spent",
        "situation",
        "stuck",
        "gently",
        "possible",
        "cell",
        "mention",
        "silent",
        "definitely",
        "rush",
        "hung",
        "brush",
        "perhaps",
        "groan",
        "ass",
        "rock",
        "card",
        "lose",
        "blush",
        "besides",
        "crazy",
        "type",
        "bore",
        "afraid",
        "chase",
        "respond",
        "marry",
        "remind",
        "pack",
        "daughter",
        "serious",
        "girlfriend",
        "mad",
        "somehow",
        "buy",
        "sent",
        "tight",
        "simply",
        "trust",
        "imagine",
        "wind",
        "chuckle",
        "bar",
        "pink",
        "shove",
        "ball",
        "sight",
        "drag",
        "they'd",
        "human",
        "truth",
        "share",
        "area",
        "concern",
        "shouldn't",
        "team",
        "escape",
        "mumble",
        "often",
        "search",
        "apparently",
        "attempt",
        "son",
        "within",
        "band",
        "cute",
        "led",
        "memory",
        "anger",
        "fly",
        "paint",
        "bottle",
        "busy",
        "comment",
        "exclaim",
        "avoid",
        "grow",
        "grey",
        "mirror",
        "gasp",
        "hallway",
        "dear",
        "star",
        "sick",
        "cat",
        "counter",
        "interrupt",
        "none",
        "blink",
        "spend",
        "usual",
        "worse",
        "locker",
        "important",
        "favorite",
        "grip",
        "TV",
        "ice",
        "pretend",
        "settle",
        "amaze",
        "pop",
        "disappear",
        "carefully",
        "train",
        "stick",
        "guard",
        "teeth",
        "flash",
        "uncle",
        "send",
        "doubt",
        "visit",
        "nervous",
        "excite",
        "approach",
        "excuse",
        "fit",
        "noise",
        "study",
        "letter",
        "police",
        "eventually",
        "burn",
        "field",
        "hospital",
        "tie",
        "summer",
        "huh",
        "shift",
        "self",
        "hurry",
        "greet",
        "wife",
        "position",
        "we've",
        "wipe",
        "heavy",
        "slam",
        "broken",
        "complete",
        "space",
        "brain",
        "tiny",
        "pants",
        "ah",
        "punch",
        "shower",
        "tongue",
        "afternoon",
        "seriously",
        "cup",
        "further",
        "race",
        "recognize",
        "computer",
        "rang",
        "safe",
        "jacket",
        "bottom",
        "hundred",
        "relax",
        "sudden",
        "wow",
        "college",
        "flip",
        "mood",
        "track",
        "crack",
        "block",
        "handle",
        "themselves",
        "drove",
        "seven",
        "struggle",
        "whether",
        "ahead",
        "sad",
        "dry",
        "women",
        "focus",
        "repeat",
        "thick",
        "relationship",
        "jerk",
        "present",
        "suck",
        "bell",
        "surround",
        "evening",
        "bite",
        "single",
        "fault",
        "shadow",
        "wood",
        "easily",
        "woke",
        "smoke",
        "draw",
        "suggest",
        "wet",
        "accept",
        "third",
        "totally",
        "wore",
        "breakfast",
        "trail",
        "animal",
        "warn",
        "aunt",
        "sir",
        "piss",
        "burst",
        "match",
        "fix",
        "practically",
        "odd",
        "wash",
        "sing",
        "inch",
        "size",
        "secret",
        "who's",
        "clock",
        "company",
        "view",
        "suit",
        "forever",
        "familiar",
        "forehead",
        "shoot",
        "grew",
        "stretch",
        "pound",
        "despite",
        "response",
        "center",
        "curl",
        "slight",
        "toss",
        "beneath",
        "fist",
        "welcome",
        "laughter",
        "angel",
        "Christmas",
        "we'd",
        "main",
        "simple",
        "neither",
        "distance",
        "comfort",
        "upset",
        "assume",
        "eight",
        "gather",
        "lucky",
        "fade",
        "Ms.",
        "coat",
        "special",
        "awkward",
        "certain",
        "plate",
        "darkness",
        "practice",
        "obvious",
        "grade",
        "cream",
        "choice",
        "hardly",
        "pale",
        "thin",
        "button",
        "chocolate",
        "refuse",
        "slid",
        "pillow",
        "thirty",
        "count",
        "honestly",
        "poor",
        "motion",
        "storm",
        "lightly",
        "nobody",
        "experience",
        "path",
        "period",
        "dare",
        "demand",
        "comfortable",
        "clearly",
        "silver",
        "peer",
        "birthday",
        "disgust",
        "embarrass",
        "bought",
        "test",
        "lap",
        "bet",
        "loudly",
        "driver",
        "murmur",
        "taste",
        "perfectly",
        "squeeze",
        "board",
        "worth",
        "fold",
        "spread",
        "crap",
        "emotion",
        "subject",
        "pour",
        "laid",
        "lower",
        "mile",
        "yea",
        "page",
        "pile",
        "snow",
        "message",
        "English",
        "scene",
        "sink",
        "fail",
        "forgot",
        "hole",
        "silently",
        "heat",
        "weekend",
        "drew",
        "guitar",
        "sweat",
        "unless",
        "cloud",
        "waist",
        "slap",
        "argue",
        "grass",
        "idiot",
        "screen",
        "yesterday",
        "swear",
        "twin",
        "instantly",
        "apart",
        "narrow",
        "opposite",
        "blow",
        "wrist",
        "earth",
        "action",
        "circle",
        "forgotten",
        "list",
        "closet",
        "drunk",
        "shape",
        "yellow",
        "twist",
        "weight",
        "smart",
        "it'll",
        "treat",
        "pool",
        "prepare",
        "awake",
        "certainly",
        "tease",
        "contact",
        "slide",
        "wonderful",
        "bitch",
        "reveal",
        "swing",
        "truck",
        "anywhere",
        "flower",
        "upstairs",
        "hers",
        "itself",
        "wander",
        "downstairs",
        "football",
        "possibly",
        "rip",
        "forest",
        "mostly",
        "bloody",
        "church",
        "gay",
        "stone",
        "husband",
        "sex",
        "trick",
        "yours",
        "growl",
        "club",
        "Friday",
        "stage",
        "include",
        "sip",
        "invite",
        "sharp",
        "convince",
        "sheet",
        "absolutely",
        "orange",
        "relief",
        "apologize",
        "art",
        "he'll",
        "remove",
        "crash",
        "van",
        "curse",
        "alive",
        "blanket",
        "receive",
        "tip",
        "rise",
        "tightly",
        "waste",
        "bowl",
        "fallen",
        "river",
        "mama",
        "pace",
        "honey",
        "swallow",
        "king",
        "camera",
        "deserve",
        "dirty",
        "chin",
        "doorway",
        "image",
        "cookie",
        "homework",
        "hat",
        "luck",
        "aside",
        "information",
        "fifteen",
        "fair",
        "player",
        "monster",
        "gate",
        "win",
        "below",
        "ceiling",
        "click",
        "cook",
        "travel",
        "fish",
        "lit",
        "nervously",
        "towel",
        "shiver",
        "final",
        "horrible",
        "station",
        "camp",
        "hungry",
        "thousand",
        "evil",
        "rich",
        "war",
        "involve",
        "jaw",
        "uncomfortable",
        "directly",
        "level",
        "double",
        "nine",
        "creature",
        "glow",
        "somewhat",
        "blame",
        "entrance",
        "hip",
        "fresh",
        "hiss",
        "normally",
        "tap",
        "machine",
        "ruin",
        "bear",
        "rule",
        "till",
        "cock",
        "stumble",
        "complain",
        "everybody",
        "truly",
        "nurse",
        "speed",
        "hmm",
        "panic",
        "smooth",
        "weak",
        "good-bye",
        "would've",
        "extra",
        "gesture",
        "scowl",
        "beer",
        "release",
        "country",
        "officer",
        "careful",
        "create",
        "hill",
        "snort",
        "flew",
        "heel",
        "brow",
        "charge",
        "flat",
        "plus",
        "switch",
        "whenever",
        "drift",
        "metal",
        "discover",
        "wheel",
        "skirt",
        "pat",
        "ate",
        "tea",
        "hotel",
        "sob",
        "future",
        "record",
        "boot",
        "likely",
        "cheer",
        "gold",
        "prove",
        "ha",
        "twice",
        "aware",
        "lack",
        "princess",
        "bench",
        "cousin",
        "detail",
        "amount",
        "bird",
        "backward",
        "crush",
        "cigarette",
        "faint",
        "belong",
        "stranger",
        "beach",
        "load",
        "everywhere",
        "scratch",
        "history",
        "restaurant",
        "event",
        "extremely",
        "widen",
        "clutch",
        "due",
        "tug",
        "beyond",
        "happily",
        "mistake",
        "palm",
        "amuse",
        "guest",
        "Saturday",
        "wooden",
        "worst",
        "exit",
        "plastic",
        "reality",
        "wince",
        "announce",
        "gotta",
        "slept",
        "she'll",
        "member",
        "choose",
        "Dr.",
        "swim",
        "alarm",
        "crawl",
        "dollar",
        "knife",
        "magic",
        "paid",
        "pizza",
        "purse",
        "gift",
        "chicken",
        "plane",
        "choke",
        "screw",
        "protest",
        "base",
        "drug",
        "introduce",
        "sleeve",
        "movement",
        "loose",
        "bare",
        "wanna",
        "difficult",
        "frame",
        "spin",
        "fake",
        "pen",
        "understood",
        "nor",
        "unfortunately",
        "written",
        "decision",
        "beg",
        "heavily",
        "insist",
        "soul",
        "random",
        "sport",
        "male",
        "urge",
        "million",
        "yawn",
        "backpack",
        "judge",
        "startle",
        "bunch",
        "stream",
        "they'll",
        "muscle",
        "yard",
        "accident",
        "dragon",
        "sentence",
        "fool",
        "torn",
        "bow",
        "echo",
        "mix",
        "bury",
        "system",
        "dirt",
        "spirit",
        "leaf",
        "protect",
        "row",
        "forth",
        "purple",
        "bang",
        "curious",
        "nearby",
        "nowhere",
        "collapse",
        "hop",
        "proud",
        "wing",
        "destroy",
        "sea",
        "separate",
        "silly",
        "wound",
        "honest",
        "battle",
        "born",
        "cough",
        "mountain",
        "split",
        "square",
        "underneath",
        "bike",
        "process",
        "somebody",
        "classroom",
        "presence",
        "whose",
        "grown",
        "hidden",
        "serve",
        "female",
        "garden",
        "meal",
        "unable",
        "elbow",
        "support",
        "bridge",
        "reaction",
        "skip",
        "wild",
        "angrily",
        "effect",
        "threaten",
        "basically",
        "smack",
        "stroke",
        "flow",
        "moan",
        "plant",
        "impossible",
        "bruise",
        "disappoint",
        "energy",
        "relieve",
        "confusion",
        "wedding",
        "fat",
        "bill",
        "dude",
        "address",
        "cast",
        "naked",
        "toy",
        "math",
        "personal",
        "ship",
        "spun",
        "chat",
        "pray",
        "whip",
        "grasp",
        "hasn't",
        "float",
        "fully",
        "gorgeous",
        "indeed",
        "nail",
        "vision",
        "innocent",
        "friendly",
        "jealous",
        "swung",
        "flame",
        "dorm",
        "driveway",
        "spill",
        "gang",
        "murder",
        "respect",
        "bent",
        "tail",
        "inform",
        "lesson",
        "whine",
        "clench",
        "excitement",
        "library",
        "lord",
        "surface",
        "dust",
        "dump",
        "feature",
        "object",
        "weapon",
        "calmly",
        "hesitate",
        "hint",
        "law",
        "magazine",
        "among",
        "boss",
        "file",
        "leather",
        "result",
        "thrown",
        "toe",
        "terrible",
        "local",
        "project",
        "won",
        "radio",
        "regret",
        "grumble",
        "otherwise",
        "ridiculous",
        "CD",
        "lovely",
        "mock",
        "effort",
        "fan",
        "nerve",
        "report",
        "stall",
        "elevator",
        "mate",
        "bastard",
        "grunt",
        "o'clock",
        "rope",
        "entirely",
        "frighten",
        "shade",
        "strength",
        "bone",
        "exchange",
        "flight",
        "Monday",
        "partner",
        "plain",
        "shine",
        "cafeteria",
        "beam",
        "exist",
        "porch",
        "queen",
        "squeal",
        "faith",
        "pierce",
        "remark",
        "content",
        "ease",
        "flick",
        "mall",
        "cannot",
        "carpet",
        "length",
        "replace",
        "duck",
        "bump",
        "common",
        "style",
        "tan",
        "cake",
        "court",
        "previous",
        "balance",
        "bank",
        "blind",
        "dangerous",
        "particular",
        "sell",
        "wrote",
        "distract",
        "melt",
        "popular",
        "social",
        "teach",
        "appearance",
        "correct",
        "lake",
        "public",
        "sarcastically",
        "guilty",
        "kinda",
        "shall",
        "television",
        "boat",
        "firmly",
        "tent",
        "thumb",
        "manner",
        "flush",
        "roof",
        "schedule",
        "dine",
        "weather",
        "casually",
        "moon",
        "difference",
        "butt",
        "charm",
        "feed",
        "frustration",
        "gentle",
        "hook",
        "bounce",
        "particularly",
        "pleasure",
        "sneak",
        "leader",
        "rage",
        "shriek",
        "suffer",
        "Sunday",
        "argument",
        "pregnant",
        "discuss",
        "statement",
        "ticket",
        "dig",
        "doll",
        "chill",
        "fence",
        "horror",
        "built",
        "cop",
        "security",
        "sidewalk",
        "breast",
        "curtain",
        "whom",
        "fifty",
        "giant",
        "milk",
        "recall",
        "term",
        "footstep",
        "stun",
        "tuck",
        "clothing",
        "lick",
        "joy",
        "ugly",
        "hopefully",
        "soldier",
        "plead",
        "struck",
        "trap",
        "opinion",
        "plenty",
        "tank",
        "breeze",
        "awesome",
        "desire",
        "roommate",
        "halfway",
        "opportunity",
        "outfit",
        "rough",
        "ain't",
        "beauty",
        "chose",
        "snake",
        "tape",
        "badly",
        "cheat",
        "daddy",
        "roar",
        "describe",
        "desperately",
        "height",
        "thigh",
        "tilt",
        "deeply",
        "friendship",
        "winter",
        "witch",
        "worn",
        "condition",
        "enemy",
        "golden",
        "sofa",
        "master",
        "rude",
        "throughout",
        "assure",
        "damage",
        "natural",
        "steal",
        "belt",
        "cage",
        "claim",
        "nightmare",
        "prefer",
        "purpose",
        "merely",
        "pin",
        "French",
        "sadly",
        "uniform",
        "branch",
        "direct",
        "hunter",
        "juice",
        "character",
        "pure",
        "stain",
        "various",
        "gain",
        "soak",
        "lately",
        "pitch",
        "accent",
        "they've",
        "tremble",
        "cabin",
        "chew",
        "physical",
        "puzzle",
        "explode",
        "steady",
        "how's",
        "pet",
        "sake",
        "compare",
        "principal",
        "scan",
        "forty",
        "impress",
        "mentally",
        "react",
        "sandwich",
        "shy",
        "twelve",
        "whilst",
        "bullet",
        "challenge",
        "command",
        "examine",
        "film",
        "appreciate",
        "tense",
        "blank",
        "blew",
        "fought",
        "gym",
        "passenger",
        "teenager",
        "dish",
        "drawn",
        "scary",
        "unlike",
        "straighten",
        "strain",
        "tune",
        "constantly",
        "famous",
        "marriage",
        "bound",
        "fancy",
        "issue",
        "warmth",
        "awhile",
        "collect",
        "concentrate",
        "copy",
        "disbelief",
        "tighten",
        "determine",
        "favor",
        "mental",
        "bush",
        "forgive",
        "aim",
        "embrace",
        "fairly",
        "froze",
        "insult",
        "option",
        "post",
        "resist",
        "spoken",
        "apple",
        "general",
        "instant",
        "jeep",
        "emerge",
        "neighbor",
        "pressure",
        "service",
        "shuffle",
        "briefly",
        "notebook",
        "peace",
        "string",
        "wine",
        "dash",
        "gut",
        "stress",
        "connect",
        "language",
        "private",
        "spring",
        "chip",
        "puppy",
        "ache",
        "desperate",
        "habit",
        "necessary",
        "nope",
        "pencil",
        "satisfy",
        "deny",
        "mommy",
        "attitude",
        "dial",
        "painful",
        "display",
        "frustrate",
        "it'd",
        "tend",
        "exact",
        "powerful",
        "nature",
        "photo",
        "total",
        "video",
        "egg",
        "occur",
        "anybody",
        "corridor",
        "gulp",
        "trace",
        "whoever",
        "brief",
        "exhaust",
        "pout",
        "terrify",
        "chapter",
        "insane",
        "spell",
        "surely",
        "tray",
        "alcohol",
        "chain",
        "fashion",
        "garage",
        "inquire",
        "candy",
        "similar",
        "bark",
        "flirt",
        "pathetic",
        "supply",
        "tower",
        "engine",
        "frozen",
        "map",
        "toilet",
        "background",
        "shudder",
        "spider",
        "adult",
        "cheap",
        "clue",
        "hazel",
        "irritate",
        "sand",
        "quarter",
        "spare",
        "American",
        "rid",
        "spat",
        "pot",
        "awful",
        "bleed",
        "fate",
        "jog",
        "strike",
        "grimace",
        "holiday",
        "whistle",
        "agreement",
        "dull",
        "expensive",
        "snatch",
        "sometime",
        "ability",
        "campus",
        "collar",
        "disturb",
        "flicker",
        "proceed",
        "recently",
        "risk",
        "skill",
        "topic",
        "defense",
        "fry",
        "luckily",
        "retort",
        "captain",
        "eaten",
        "glove",
        "mid",
        "owner",
        "cheese",
        "yank",
        "afterward",
        "closely",
        "coach",
        "feather",
        "handsome",
        "New York",
        "pity",
        "signal",
        "sniff",
        "strap",
        "contain",
        "survive",
        "sweater",
        "west",
        "drawer",
        "leap",
        "major",
        "peek",
        "suspect",
        "tour",
        "freeze",
        "heaven",
        "mask",
        "surprisingly",
        "abruptly",
        "begun",
        "customer",
        "pad",
        "design",
        "flop",
        "pride",
        "yep",
        "interview",
        "makeup",
        "blast",
        "prince",
        "rode",
        "bubble",
        "rent",
        "teen"
    };
    char[][] wordsAsChars = new char[words.length][];
    int[] frequencies = new int[words.length];
    for (int i = 0; i < stringArray.length; i++) {
        wordsAsChars[i] = words[i].toCharArray();
        // Convert rank to pseudo frequency
        frequencies = words.length - i;
    }

    mDetectorUnderTest.setWords(
        Collections.singletonList(wordsAsChars), Collections.singletonList(frequencies));

    Assert.assertEquals(GestureTypingDetector.LoadingState.LOADING, mCurrentState.get());
  }

  @After
  public void tearDown() {
    mSubscribeState.dispose();
  }

  @Test
  public void testHappyPath() {
    TestRxSchedulers.drainAllTasks();
    Assert.assertEquals(GestureTypingDetector.LoadingState.LOADED, mCurrentState.get());

    mDetectorUnderTest.clearGesture();

    AtomicInteger distance = new AtomicInteger();
    generatePointsStreamOfKeysString("helo")
        .forEach(point -> distance.addAndGet(mDetectorUnderTest.addPoint(point.x, point.y)));
    Assert.assertEquals(8016, distance.get());
    final ArrayList<String> candidates = mDetectorUnderTest.getCandidates();

    Assert.assertEquals(MAX_SUGGESTIONS, candidates.size());
    // "harp" is removed due to MAX_SUGGESTIONS limit
    Arrays.asList("hero", "hello", "hell", "Hall")
        .forEach(
            word ->
                Assert.assertTrue(
                    "Missing the word " + word + ". has " + candidates, candidates.remove(word)));
    // ensuring we asserted all words
    Assert.assertTrue("Still has " + candidates, candidates.isEmpty());
  }

  @Test
  public void testTakesWordFrequencyIntoAccount() {
    TestRxSchedulers.drainAllTasks();
    Assert.assertEquals(GestureTypingDetector.LoadingState.LOADED, mCurrentState.get());

    mDetectorUnderTest.clearGesture();

    generatePointsStreamOfKeysString("help")
        .forEach(point -> mDetectorUnderTest.addPoint(point.x, point.y));
    final ArrayList<String> candidates = mDetectorUnderTest.getCandidates();

    Assert.assertEquals(MAX_SUGGESTIONS, candidates.size());
    Assert.assertEquals("help", candidates.get(0));
    Assert.assertEquals("hell", candidates.get(1));
    Assert.assertEquals("hero", candidates.get(2));
    Assert.assertEquals("Hall", candidates.get(3));
  }

  @Test
  public void testFilterOutWordsThatDoNotStartsWithFirstPress() {
    TestRxSchedulers.drainAllTasks();
    Assert.assertEquals(GestureTypingDetector.LoadingState.LOADED, mCurrentState.get());

    mDetectorUnderTest.clearGesture();

    generatePointsStreamOfKeysString("to")
        .forEach(point -> mDetectorUnderTest.addPoint(point.x, point.y));
    final ArrayList<String> candidates = new ArrayList<>(mDetectorUnderTest.getCandidates());

    Assert.assertEquals(0, candidates.size());

    candidates.clear();
    mDetectorUnderTest.clearGesture();
    generatePointsStreamOfKeysString("god")
        .forEach(point -> mDetectorUnderTest.addPoint(point.x, point.y));
    candidates.addAll(mDetectorUnderTest.getCandidates());

    Assert.assertEquals(3, candidates.size());
    Arrays.asList("good", "God", "gods")
        .forEach(word -> Assert.assertTrue("Missing the word " + word, candidates.remove(word)));
    Assert.assertTrue("Still has " + candidates.toString(), candidates.isEmpty());
  }

  @Test
  public void testCalculatesCornersInBackground() {
    TestRxSchedulers.drainAllTasks();
    Assert.assertEquals(GestureTypingDetector.LoadingState.LOADED, mCurrentState.get());

    mDetectorUnderTest.destroy();
    TestRxSchedulers.drainAllTasks();
    Assert.assertEquals(GestureTypingDetector.LoadingState.NOT_LOADED, mCurrentState.get());
  }

  @Test
  @Ignore("I'm not sure how this is two dictionaries")
  public void testCalculatesCornersInBackgroundWithTwoDictionaries() {
    TestRxSchedulers.backgroundRunOneJob();
    Assert.assertEquals(GestureTypingDetector.LoadingState.LOADING, mCurrentState.get());
    TestRxSchedulers.backgroundRunOneJob();
    Assert.assertEquals(GestureTypingDetector.LoadingState.LOADED, mCurrentState.get());
    mDetectorUnderTest.destroy();
    TestRxSchedulers.drainAllTasks();
    Assert.assertEquals(GestureTypingDetector.LoadingState.NOT_LOADED, mCurrentState.get());
  }

  @Test
  @Ignore("I'm not sure how this is two dictionaries")
  public void testCalculatesCornersInBackgroundWithTwoDictionariesButDisposed() {
    TestRxSchedulers.backgroundRunOneJob();
    mSubscribeState.dispose();
    Assert.assertEquals(GestureTypingDetector.LoadingState.LOADING, mCurrentState.get());
    TestRxSchedulers.backgroundRunOneJob();
    Assert.assertEquals(GestureTypingDetector.LoadingState.LOADING, mCurrentState.get());
    mDetectorUnderTest.destroy();
    TestRxSchedulers.drainAllTasks();
    Assert.assertEquals(GestureTypingDetector.LoadingState.LOADING, mCurrentState.get());
  }

  @Test
  public void testCalculatesCornersInBackgroundWithTwoDictionariesButDestroyed() {
    TestRxSchedulers.drainAllTasks();
    mDetectorUnderTest.destroy();
    Assert.assertEquals(GestureTypingDetector.LoadingState.NOT_LOADED, mCurrentState.get());
    TestRxSchedulers.drainAllTasks();
    Assert.assertEquals(GestureTypingDetector.LoadingState.NOT_LOADED, mCurrentState.get());
    TestRxSchedulers.drainAllTasks();
    mSubscribeState.dispose();

    TestRxSchedulers.drainAllTasks();
    Assert.assertEquals(GestureTypingDetector.LoadingState.NOT_LOADED, mCurrentState.get());
  }

  @Test
  public void testHasEnoughCurvatureStraight() {
    final int[] Xs = new int[3];
    final int[] Ys = new int[3];

    Xs[0] = -100;
    Ys[0] = 0;

    Xs[1] = 0;
    Ys[1] = 0;

    Xs[2] = 100;
    Ys[2] = 0;
    Assert.assertFalse(GestureTypingDetector.hasEnoughCurvature(Xs, Ys, 1));

    Xs[0] = 0;
    Ys[0] = -100;

    Xs[1] = 0;
    Ys[1] = 0;

    Xs[2] = 0;
    Ys[2] = 100;
    Assert.assertFalse(GestureTypingDetector.hasEnoughCurvature(Xs, Ys, 1));

    Xs[0] = 50;
    Ys[0] = -50;

    Xs[1] = 0;
    Ys[1] = 0;

    Xs[2] = -50;
    Ys[2] = 50;
    Assert.assertFalse(GestureTypingDetector.hasEnoughCurvature(Xs, Ys, 1));

    Xs[0] = -50;
    Ys[0] = 50;

    Xs[1] = 0;
    Ys[1] = 0;

    Xs[2] = 50;
    Ys[2] = -50;
    Assert.assertFalse(GestureTypingDetector.hasEnoughCurvature(Xs, Ys, 1));

    Xs[0] = -41;
    Ys[0] = 50;

    Xs[1] = 9;
    Ys[1] = 0;

    Xs[2] = 59;
    Ys[2] = -50;
    Assert.assertFalse(GestureTypingDetector.hasEnoughCurvature(Xs, Ys, 1));
  }

  @Test
  public void testHasEnoughCurvature90Degrees() {
    final int[] Xs = new int[3];
    final int[] Ys = new int[3];

    Xs[0] = -50;
    Ys[0] = 0;

    Xs[1] = 0;
    Ys[1] = 0;

    Xs[2] = 0;
    Ys[2] = -50;
    Assert.assertTrue(GestureTypingDetector.hasEnoughCurvature(Xs, Ys, 1));

    Xs[0] = -50;
    Ys[0] = 0;

    Xs[1] = 0;
    Ys[1] = 0;

    Xs[2] = 0;
    Ys[2] = 50;
    Assert.assertTrue(GestureTypingDetector.hasEnoughCurvature(Xs, Ys, 1));

    Xs[0] = 0;
    Ys[0] = -50;

    Xs[1] = 0;
    Ys[1] = 0;

    Xs[2] = 50;
    Ys[2] = 0;
    Assert.assertTrue(GestureTypingDetector.hasEnoughCurvature(Xs, Ys, 1));
  }

  @Test
  public void testHasEnoughCurvature180Degrees() {
    final int[] Xs = new int[3];
    final int[] Ys = new int[3];

    Xs[0] = 0;
    Ys[0] = -50;

    Xs[1] = 0;
    Ys[1] = 0;

    Xs[2] = 0;
    Ys[2] = -50;
    Assert.assertTrue(GestureTypingDetector.hasEnoughCurvature(Xs, Ys, 1));

    Xs[0] = -50;
    Ys[0] = 0;

    Xs[1] = 0;
    Ys[1] = 0;

    Xs[2] = -50;
    Ys[2] = 0;
    Assert.assertTrue(GestureTypingDetector.hasEnoughCurvature(Xs, Ys, 1));
  }

  @Test
  public void testHasEnoughCurvature15Degrees() {
    final int[] Xs = new int[3];
    final int[] Ys = new int[3];

    // https://www.triangle-calculator.com/?what=&q=A%3D165%2C+b%3D100%2C+c%3D100&submit=Solve
    // A[100; 0] B[0; 0] C[196.593; 25.882]

    Xs[0] = 0;
    Ys[0] = 0;

    Xs[1] = 100;
    Ys[1] = 0;

    Xs[2] = 196;
    Ys[2] = 26;
    Assert.assertTrue(GestureTypingDetector.hasEnoughCurvature(Xs, Ys, 1));

    Xs[0] = 0;
    Ys[0] = 0;

    Xs[1] = 100;
    Ys[1] = 0;

    Xs[2] = 196;
    Ys[2] = -26;
    Assert.assertTrue(GestureTypingDetector.hasEnoughCurvature(Xs, Ys, 1));
  }

  @Test
  public void testHasEnoughCurvature9Degrees() {
    final int[] Xs = new int[3];
    final int[] Ys = new int[3];

    // https://www.triangle-calculator.com/?what=&q=A%3D171%2C+b%3D100%2C+c%3D100&submit=Solve
    // A[100; 0] B[0; 0] C[198.769; 15.643]

    Xs[0] = 0;
    Ys[0] = 0;

    Xs[1] = 100;
    Ys[1] = 0;

    Xs[2] = 198;
    Ys[2] = 16;
    Assert.assertFalse(GestureTypingDetector.hasEnoughCurvature(Xs, Ys, 1));

    Xs[0] = 0;
    Ys[0] = 0;

    Xs[1] = 100;
    Ys[1] = 0;

    Xs[2] = 198;
    Ys[2] = -16;
    Assert.assertFalse(GestureTypingDetector.hasEnoughCurvature(Xs, Ys, 1));
  }

  private Stream<Point> generatePointsStreamOfKeysString(String path) {
    return path.chars()
        .boxed()
        .map(this::getPointForCharacter)
        .map(
            new Function<Point, Pair<Point, Point>>() {
              private Point mPrevious = new Point();

              @Override
              public Pair<Point, Point> apply(Point point) {
                final Point previous = mPrevious;
                mPrevious = point;

                return new Pair<>(previous, mPrevious);
              }
            })
        .skip(1 /*the first one is just wrong*/)
        .map(pair -> generateTraceBetweenPoints(pair.first, pair.second))
        .flatMap(pointStream -> pointStream);
  }
}
